### ISSUE TITLE
为什么复现不出论文的结果啊

### ISSUE THREAD

**Issue by StarryNight1123** [guokan987/COGCN#1]
感觉每个数据集跑出来都差很多 已经按照论文里给的参数设置了

**Comment by guokan987** [comment]
感谢您关注我们的工作（实际上我已经很久没看这个代码啦），可能跟环境与版本都有关系（随机性比较大（跟dropout有关系）），我在本地，运行了test.py，确实测试出了我当时保存的模型性能，您这边如果要对比我这个方法，可以你的环境跑出的实际结果为准，-v-！
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/d14a0248-cb09-418e-bd5c-4eb47688cdc5" />
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/df58c309-c9cb-4f88-9175-994109d20e73" />

**Comment by StarryNight1123** [comment]
谢谢您的答复 换了环境之后能复现了
